.TH CCOL_CREATE_CHTTPCLIENT 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
ccol_create_chttpclient \- create an HTTP client with the default allocator
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

chttpcli ccol_create_chttpclient(char **err_str);
.fi
.SH DESCRIPTION
.nf
This is an inline wrapper around ccol_create_chttpclient_mp. It gives
NULL for mprocs.
.fi
.SH RETURN VALUE
.nf
A new client handle, or CHTTPCLI_INVALID if the call fails.
.fi
.SH "SEE ALSO"
.BR ccol_create_chttpclient_mp (3)
