.TH CHTTPCLI_DECLARE 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
chttpcli_declare \- declare a chttpcli handle variable
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

chttpcli_declare(name)
.fi
.SH DESCRIPTION
.nf
This macro declares a chttpcli variable with the name name. The
variable has no value yet. The macro is the same as the text
"chttpcli name;".
.fi
.SH "SEE ALSO"
.BR chttpcli_construct (3),
.BR chttpcli_declare_scoped (3)
