.TH CHTTP_REQUEST_FREE 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
chttp_request_free \- free an HTTP request and every resource that it owns
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

void chttp_request_free(chttp_request_t *req);
.fi
.SH DESCRIPTION
.nf
This function frees the copy of the URL, the copy of the body data,
the copy of content_type, the map of the headers and the request
struct itself, and also the private copy of mprocs, if the library
allocated one.

A call with NULL is safe.
.fi
.SH "SEE ALSO"
.BR chttp_request_new_mp (3)
