.TH CHTTPCLI_DECLARE_SCOPED 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
chttpcli_declare_scoped \- declare a scoped chttpcli handle variable
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

chttpcli_declare_scoped(name)
.fi
.SH DESCRIPTION
.nf
This macro declares a chttpcli variable with the name name. It uses
the cleanup attribute of GCC for an automatic destroy. The library
destroys the handle when name goes out of the scope, and it destroys
the handle in the same way as chttpclient_destroy. This happens
whatever path leaves the scope.

The macro sets the variable to CHTTPCLI_INVALID. Set the variable to
CHTTPCLI_INVALID again before the exit of the scope to stop the
cleanup call.
.fi
.SH "SEE ALSO"
.BR chttpcli_construct_scoped (3),
.BR chttpcli_declare (3)
