.TH CHTTP_REQUEST_NEW 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
chttp_request_new \- allocate and initialize an HTTP request (default allocator)
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

chttp_request_t *chttp_request_new(chttp_method_t method,
                                   const char *url,
                                   const chttp_request_body_t *body,
                                   char **err_str);
.fi
.SH DESCRIPTION
.nf
This is an inline wrapper around chttp_request_new_mp. It gives NULL
for mprocs.
.fi
.SH RETURN VALUE
.nf
A pointer to the new request, or NULL if the call fails.
.fi
.SH "SEE ALSO"
.BR chttp_request_new_mp (3)
