.TH CHTTP_DO 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
chttp_do \- do an HTTP request with the default client
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

ccol_retval_t chttp_do(const chttp_request_t *req,
                       chttpcli_response **resp_out);
.fi
.SH DESCRIPTION
.nf
This function is the same as
chttpclient_do(chttp_default_client(), req, resp_out).
.fi
.SH RETURN VALUE
.nf
The same codes as chttpclient_do. The function gives
ccol_unexpected_failure if the library cannot initialize the default
client.
.fi
.SH "SEE ALSO"
.BR chttpclient_do (3),
.BR chttp_default_client (3)
