.TH CHTTP_POST 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
chttp_post \- do a POST request with the default client
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpclient.h>

ccol_retval_t chttp_post(const char *url,
                         const chttp_request_body_t *body,
                         chttpcli_response **resp_out);
.fi
.SH DESCRIPTION
.nf
This is a short wrapper for an HTTP POST. body can be NULL for a POST
with no body.
.fi
.SH RETURN VALUE
.nf
The same codes as chttpclient_do.
.fi
.SH "SEE ALSO"
.BR chttp_get (3),
.BR chttp_do (3)
