.TH CSTR_C_STR 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
cstr_c_str \- return a pointer to the null-terminated character data
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cstring.h>

cstr_c_str(s);
.fi
.SH DESCRIPTION
.nf
This macro is a pass-through wrapper for cstring_c_str().
.fi
.SH PARAMETERS
.nf
s   cstr to query
.fi
.SH RETURN VALUE
.nf
A pointer to the null-terminated character data
.fi
.SH NOTES
.nf
Any operation that changes the string makes the pointer invalid
.fi
.SH "SEE ALSO"
.BR cstring_c_str (3),
.BR cstr_length (3)
