.TH CSTRING_LENGTH 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cstring_length \- return the number of characters in the string
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <cstring.h>

size_t cstring_length(cstr s);
.fi
.SH DESCRIPTION
.nf
Returns the number of characters currently stored in the string, not
including the terminating null byte.
.fi
.SH PARAMETERS
.nf
s   String to query
.fi
.SH RETURN VALUE
.nf
Length in bytes (excluding null terminator)
.fi
.SH NOTES
.nf
Asserts if s is NULL
.fi
.SH "SEE ALSO"
.BR cstring_is_empty (3),
.BR cstring_c_str (3)
