.TH CSTR_INSERT 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
cstr_insert \- insert a C string at a position; calls fatal_err() on failure
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <cstring.h>

cstr_insert(s, pos, str);
.fi
.SH DESCRIPTION
.nf
Calls cstring_insert() and calls fatal_err() if the return value is not
ccol_success.
.fi
.SH PARAMETERS
.nf
s     cstr to modify
pos   Insertion position (0 ... length, inclusive)
str   C string to insert (must not be NULL)
.fi
.SH NOTES
.nf
Use cstring_insert() directly if you need to handle errors gracefully
.fi
.SH "SEE ALSO"
.BR cstring_insert (3),
.BR cstr_append (3),
.BR cstr_prepend (3)
