.TH CSTR_FIND 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
cstr_find \- find the first occurrence of a substring
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cstring.h>

cstr_find(s, needle);
.fi
.SH DESCRIPTION
.nf
This macro is a pass-through wrapper for cstring_find().
.fi
.SH PARAMETERS
.nf
s        cstr to search
needle   Substring to find
.fi
.SH RETURN VALUE
.nf
The zero-based index of the first occurrence. The macro gives
ccol_invalid_size when it does not find the needle
.fi
.SH "SEE ALSO"
.BR cstring_find (3),
.BR cstr_rfind (3)
