.TH CSTRING_APPEND 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cstring_append \- append a C string to the end
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cstring.h>

ccol_retval_t cstring_append(cstr s, const char *str);
.fi
.SH DESCRIPTION
.nf
This function appends the null-terminated C string str to the end of s. The
internal buffer grows when the function needs more room.
.fi
.SH PARAMETERS
.nf
s     String to change
str   C string to append (must not be NULL)
.fi
.SH RETURN VALUE
.nf
ccol_success              - The append succeeded
ccol_invalid_args         - str is NULL
ccol_container_full       - The result overflows a size_t
ccol_not_enough_memory    - The reallocation failed
.fi
.SH NOTES
.nf
Asserts if s is NULL
.fi
.SH "SEE ALSO"
.BR cstring_prepend (3),
.BR cstring_insert (3),
.BR cstring_set (3)
