.TH CSTRING_COMPARE 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cstring_compare \- compare the string to a C string
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cstring.h>

int cstring_compare(cstr s, const char *str);
.fi
.SH DESCRIPTION
.nf
This function compares the content of s to the null-terminated C string str.
The semantics are the semantics of strcmp().
.fi
.SH PARAMETERS
.nf
s     String to compare
str   C string to compare against
.fi
.SH RETURN VALUE
.nf
A negative value if s < str
Zero if s == str
A positive value if s > str
1 if str is NULL. The library treats a non-null string as greater than NULL
.fi
.SH NOTES
.nf
Asserts if s is NULL
.fi
.SH "SEE ALSO"
.BR cstring_equals (3),
.BR cstring_starts_with (3),
.BR cstring_ends_with (3)
