.TH CCOL_CHAN_DISABLE_SENDING 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
ccol_chan_disable_sending \- turn off sends on a ccol_channel direction
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cthreadcomm.h>

ccol_retval_t ccol_chan_disable_sending(ccol_channel *ch, ccol_channel_direction d);
.fi
.SH DESCRIPTION
.nf
This function stops all new sends on the given direction and wakes
every thread that blocks inside a send on that direction.
.fi
.SH PARAMETERS
.nf
ch   Channel to change
d    Direction that gets sends turned off (ccol_owner_to_workers or
     ccol_workers_to_owner)
.fi
.SH RETURN VALUE
.nf
ccol_success       - The function turned sends off
ccol_invalid_args  - ch is NULL, or d is not valid
.fi
.SH NOTES
.nf
The function wakes every blocked sender on the given direction and
does not change the other direction. ccol_chan_enable_sending() turns
sends on again.
.fi
.SH "SEE ALSO"
.BR ccol_chan_enable_sending (3)
