.TH CHAN_DISABLE_SENDING 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
chan_disable_sending \- disable sending on a channel direction
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <cthreadcomm.h>

ccol_retval_t chan_disable_sending(channel *ch, channel_direction d);
.fi
.SH DESCRIPTION
.nf
Prevents new send operations on the specified direction and wakes all
threads currently blocked in send operations on that direction.
.fi
.SH PARAMETERS
.nf
ch   Channel to modify
d    Direction to disable (owner_to_workers or workers_to_owner)
.fi
.SH RETURN VALUE
.nf
ccol_success       - Sending disabled successfully
ccol_invalid_args  - ch is NULL or d is invalid
.fi
.SH NOTES
.nf
Wakes all blocked senders on the specified direction
Can be re-enabled with chan_enable_sending()
Does not affect the opposite direction
.fi
.SH "SEE ALSO"
.BR chan_enable_sending (3)
