.TH CCOL_CREATE_CHTTPSVR 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
ccol_create_chttpsvr \- create an HTTP server with the default allocator
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpserver.h>

chttpsvr ccol_create_chttpsvr(clog cl, char **err_str);
.fi
.SH DESCRIPTION
.nf
This is an inline wrapper for ccol_create_chttpsvr_mp with mprocs set
to NULL.

cl may be CLOG_INVALID.  See ccol_create_chttpsvr_mp for the rules
that govern the logger.
.fi
.SH RETURN VALUE
.nf
A valid chttpsvr handle on success, or CHTTPSVR_INVALID on a failure.
.fi
.SH "SEE ALSO"
.BR ccol_create_chttpsvr_mp (3)
