.TH CHTTPSVR_DECLARE 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
chttpsvr_declare \- declare a chttpsvr variable that is not initialized
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttpserver.h>

chttpsvr_declare(name);
.fi
.SH DESCRIPTION
.nf
Declares a chttpsvr variable with the name name.  It does not
initialize that variable.  Use ccol_create_chttpsvr to initialize it
later.
.fi
.SH "SEE ALSO"
.BR chttpsvr_construct (3),
.BR ccol_create_chttpsvr (3)
