.TH ___CTPOOL_DESTROY 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
___ctpool_destroy \- RAII cleanup function for ctpool
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <cthreadpool.h>

___ctpool_destroy(ctpool *pp);
.fi
.SH DESCRIPTION
.nf
Static inline function used as the cleanup callback in
ctpool_declare_scoped() and ctpool_construct_scoped(). If *pp is
non-NULL, calls __ctpool_destroy(*pp) and sets *pp to NULL.

This function is not intended to be called directly; use
ctpool_declare_scoped() or ctpool_construct_scoped() instead.
.fi
.SH PARAMETERS
.nf
pp  Pointer to a ctpool variable (must not be NULL).
.fi
.SH NOTES
.nf
Compatible with __attribute__((cleanup)) on GCC and Clang.
.fi
.SH "SEE ALSO"
.BR ctpool_declare_scoped (3),
.BR ctpool_construct_scoped (3),
.BR ctpool_destroy (3)
