.TH CHTTP_TEXT_BODY 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
CHTTP_TEXT_BODY \- construct a chttp_request_body_t for plain-text content
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <chttp.h>

CHTTP_TEXT_BODY(d, n)
.fi
.SH DESCRIPTION
.nf
Expands to a chttp_request_body_t initialiser with Content-Type set to
"text/plain", data pointer d, and byte length n.
.fi
.SH "SEE ALSO"
.BR CHTTP_JSON_BODY (3),
.BR CHTTP_BODY (3)
