.TH CTPOOL_PENDING_COUNT 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
ctpool_pending_count \- number of tasks in the queue
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <cthreadpool.h>

size_t ctpool_pending_count(ctpool pool);
.fi
.SH DESCRIPTION
.nf
Returns a snapshot of the number of tasks currently in the task queue
(submitted but not yet picked up by a worker thread). The value may
change immediately after the call returns.
.fi
.SH PARAMETERS
.nf
pool   Thread pool handle (NULL returns 0)
.fi
.SH RETURN VALUE
.nf
Number of queued tasks, or 0 if pool is NULL.
.fi
.SH "SEE ALSO"
.BR ctpool_active_count (3)
