.TH CHTTP_JSON_BODY 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
CHTTP_JSON_BODY \- construct a chttp_request_body_t for JSON content
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/chttp.h>

CHTTP_JSON_BODY(d, n)
.fi
.SH DESCRIPTION
.nf
This macro expands to an initializer for a chttp_request_body_t. It
sets Content-Type to "application/json". It sets the data pointer to d
and the byte length to n.
.fi
.SH "SEE ALSO"
.BR CHTTP_TEXT_BODY (3),
.BR CHTTP_BODY (3)
