.TH CYAML_DICTIONARY_SIZE 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cyaml_dictionary_size \- return the number of keys in a dictionary
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cyaml.h>

size_t cyaml_dictionary_size(cyaml node);
.fi
.SH DESCRIPTION
.nf
Return the number of key-value pairs in the CYAML_DICTIONARY node.  This
function calls ccol_fatal_err() when node is NULL.  It also calls
ccol_fatal_err() when the type of node is not CYAML_DICTIONARY.
.fi
.SH RETURN VALUE
.nf
Key count.  It is 0 for an empty dictionary.
.fi
.SH "SEE ALSO"
.BR cyaml_dictionary_first (3),
.BR cyaml_dictionary_get (3),
.BR cyaml_dictionary_set (3)
