.TH CYAML_LIST_LEN 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cyaml_list_len \- return the number of elements in a list
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cyaml.h>

size_t cyaml_list_len(cyaml node);
.fi
.SH DESCRIPTION
.nf
Return the number of child nodes in the CYAML_LIST node.  The function
calls ccol_fatal_err() when node is NULL, and it calls ccol_fatal_err()
as well when node is not of type CYAML_LIST.
.fi
.SH RETURN VALUE
.nf
The element count, which is 0 for an empty list.
.fi
.SH "SEE ALSO"
.BR cyaml_list_get (3),
.BR cyaml_list_push (3)
