.TH CYAML_STR_VAL 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
cyaml_str_val \- extract a string value from a CYAML_STRING node
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cyaml.h>

const char *cyaml_str_val(cyaml node);
.fi
.SH DESCRIPTION
.nf
Return a read-only pointer to the null-terminated string that node
stores.  This function calls ccol_fatal_err() when node is NULL.  It
also calls ccol_fatal_err() when the type of node is not CYAML_STRING.

The node owns the pointer that this function gives.  That pointer
becomes invalid when the caller destroys the node.  It also becomes
invalid when the caller changes the value of the node with cyaml_set().
.fi
.SH PARAMETERS
.nf
node  CYAML_STRING node.
.fi
.SH RETURN VALUE
.nf
A pointer to the internal string buffer.
.fi
.SH "SEE ALSO"
.BR cyaml_type (3),
.BR cyaml_create_string (3)
