.TH CCOL_END 3 "2026-07-10" "c_collections" "C Collections Library - Macros"
.SH NAME
ccol_end \- end sentinel for iteration
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/citerators.h>   /* or any container header */

ccol_end
.fi
.SH DESCRIPTION
.nf
This macro expands to NULL. Every container iterator is equal to NULL at
the end of the sequence.
.fi
.SH "SEE ALSO"
.BR ccol_begin (3),
.BR ccol_iter_next (3)
