.TH CCOL_MEMPOOL_CALLOC_ENTRY 3 "2026-07-10" "c_collections" "C Collections Library - Functions"
.SH NAME
ccol_mempool_calloc_entry \- allocate zero-initialized entry from pool
.SH LIBRARY
C Collections (libccollections, \-lccollections)
.SH SYNOPSIS
.nf
#include <ccollections/cmempool.h>

void *ccol_mempool_calloc_entry(ccol_mempool *mp);
.fi
.SH DESCRIPTION
.nf
This function is like ccol_mempool_alloc_entry(). It zeros the entry
before it returns.
.fi
.SH PARAMETERS
.nf
mp   Memory pool to allocate from
.fi
.SH RETURN VALUE
.nf
Returns a pointer to the zeroed entry on success
Returns NULL when the pool is empty and the fallback is off
.fi
.SH NOTES
.nf
O(1) complexity
The function zeros the whole element
Thread-safe if the pool was created with single_threaded=false
This function asserts if mp is NULL
.fi
.SH "SEE ALSO"
.BR ccol_mempool_alloc_entry (3),
.BR ccol_mempool_free_entry (3)
